### PR TITLE
Added support for the Go programming language

### PR DESCRIPTION
**Pull request by shanep**
Simple change to add support to for the Go programming language 

Support for functions, packages, structs, const, and vars.

### CODE REVIEW

**Comment by jpitchardu** [comment]
Please, I'd love this

**Comment by stmuk** [comment]
So I came to this repo with a similar patch over 5 years later to discover it was done and never merged.

I've merged your change into https://github.com/stmuk/taglist.vim

**Comment by shanep** [comment]
Awesome!

**Comment by shanep** [comment]
closing stale stuff

**Pull request closed without merging**
